### ISSUE TITLE
How to change the rendering style of the markdown, like backquote. It's strange to have two `` besides...

### ISSUE THREAD

**Issue by 15921483570** [slidevjs/slidev#1053]
```
I hope to show code between ` at least like github, 

which do NOT have the backquote sign besides, like ` abc `.

Ideally it should be a red or orange like font color with bold style.

How to fix it? I didn't find any css setups...
```

**Comment by jstevej** [comment]
Is this really an enhancement? It seems like a bug to me.

To clarify, the following markdown:

```
Here is some `quoted` text.
```

Renders like this:

<img width="356" alt="Screenshot 2023-08-01 at 9 25 38 PM" src="https://github.com/slidevjs/slidev/assets/12628392/be719469-4e53-4394-badc-cf12ca4061c6">

The issue is that the backtick characters get rendered, but I don't think they should be.

**Comment by barraponto** [comment]
The apple-basic theme actually applies the backticks via CSS
I'm fixing it via CSS:

```
:not(pre) > code::before,
:not(pre) > code::after {
    content: '';
}
```
