### ISSUE TITLE
Components folder next to entry file not being read

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#1096]
Only the components folder in the project root is being read. But a project can have many folders with their own entries. Like presentation1/slides.md and presentation2/slides.md. All other folders are being used relative to the entry like public, setup, layouts and styles. But components is the only one that isn't being read.

components and layouts should first be checked in the directory next to the entry, and if it's not there it should check components and layouts in the project root, then in the configured theme.

https://github.com/slidevjs/slidev/issues/998

**Comment by kaakaa** [comment]
Additionally, this behavior is different between `slidev [entry]` and `slidev build [entry]`. When an entry file is in subdirectory (e.g.: `sub/slides.md`), `slidev build sub/slidex.md` reads custom components from `sub/components/*`, however, `slidev sub/slides.md` reads it from `components/*`.

The following repository is for reproducing this.
https://github.com/kaakaa/slidev-issue-1096

This is caused by missing `root: options.userRoot` in `slidev/packages/slidev/node/server.ts`. This difference seemed to be introduced by #544.

https://github.com/slidevjs/slidev/blob/6805906bb7131eea54efbd3bf22437ce571cb884/packages/slidev/node/build.ts#L35-L37

https://github.com/slidevjs/slidev/blob/6805906bb7131eea54efbd3bf22437ce571cb884/packages/slidev/node/server.ts#L23-L25

I'll create PR for this.

**Comment by rightaway** [comment]
@kaakaa do you get an error like this on `slidev build` for a custom component?

```
[Vue warn]: Failed to resolve component: CustomComponent
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
```

**Comment by rightaway** [comment]
@antfu what commit fixed this?
