### ISSUE TITLE
White margins in exported PDF

### ISSUE THREAD

**Issue by Envek** [slidevjs/slidev#1154]
**Describe the bug**
Generated PDF has white margins on right and bottom which I didn't expect.

It might be specific for my local machine, but I have no idea how to debug styling issues with PDF export.

File attached: [slides-export.pdf](https://github.com/slidevjs/slidev/files/12905728/slides-export.pdf)

Screenshot:
![Screen Shot 2023-10-14 at 22 26 54](https://github.com/slidevjs/slidev/assets/264400/428684d2-5653-4772-b898-07e6bc9319c8)

**To Reproduce**
 1. Generate new slides with `pnpm create slidev` using defaults
 2. Add playwright to dev dependencies: `pnpm i -D playwright-chromium`
 3. Run export: `pnpm run export`

**Desktop:**
 - OS: Manjaro Linux
 - Browser: playwright/chromium 1.39.0
 - Slidev version: 0.43.7

**Comment by Envek** [comment]
Interesting that if it is exported with `--per-slide` option, there are no margins (but no metadata either)

**Comment by 0phoff** [comment]
A common issue with exports is if an element in the slide (eg background image) overflows the slide container.
IIRC, exporting with `--per-slide` works because it shows each slide separately in a container which has an `overflow: hidden` on it.

As this is the demo example slidev ships with, this should probably be fixed though! :blush:

**Comment by KermanX** [comment]
I can't reproduce it on `Edge121`, `Windows11` and `Slidev0.47.4`.

The devtool shows that when exporting slides without `--per-slide`, the slides are still wrapped in an `overflow: hidden` element:

![image](https://github.com/slidevjs/slidev/assets/63178754/a8e003c0-be3e-44b5-8721-759101e993cf)

Also, since #1220 is merged, there is a workaround now if the bug still happens.
