### ISSUE TITLE
How to globally set up clicking on the page to trigger the next step function, just like in PowerPoint

### ISSUE THREAD

**Issue by SanGongHappy** [slidevjs/slidev#1226]
like title

**Comment by KermanX** [comment]
Click the red area in the following picture to go backward, and click the blue area to go forward.

![image](https://github.com/slidevjs/slidev/assets/63178754/34786691-2594-4591-8003-cb565b3e3dfe)

**Comment by KermanX** [comment]
I think clicking on the slide content to jump to the next step is hard to implement, because there seems to be no way for parent elements' event listener to know whether the event has been "received" (**NOT "prevented", because we can force users to add a `.prevent` modifier on each of the event listeners**).

Close this for now.
