### ISSUE TITLE
Assets support with Mermaid graphs

### ISSUE THREAD

**Issue by nlohya** [slidevjs/slidev#1237]
**Is your feature request related to a problem? Please describe.**

When building the project, HTML image tags used in mermaid's graphs are not supported (the asset URL is not getting updated unlike other HTML elements outside mermaid code). Which is obvious because it is inside a code block, but it would be great to support it specifically in this kind of use case.

Example

Working HTML element in the DOM after building (code outside of mermaid)
`<img src="/base-path/assets/image-XXXXX.png" />`
                  ^
                   |_____  Correctly updated path 

Not working HTML element in the DOM after building (code inside of mermaid)
`<img src="/images/image.png" />`
                  ^
                   |_____  Still local project path

**Describe the solution you'd like**
Having a configuration to allow support or direct support of assets inside Mermaid code blocks

Example of what it could look like :

```md
[//]: # (SUPPORT_HTML)
```mermaid

graph LR;

Node1{Node1} --> Node2(Node2 <img src='/images/image.png/>);
...

```

**Describe alternatives you've considered**

Currently using mermaid to create the graph then screenshotting it. 

**Awesome project by the  way. Keep up the good work 💛**

**Comment by KermanX** [comment]
I think this is very meaningful. I can think of two possible solutions at the moment:

- Rendering Mermaid in the Node.js environment, so that Vite can replace the URLs just like in normal code. But all the libraries that render Mermaid in the Node.js env require a headless browser, e.g. https://github.com/KermanX/node-mermaid-render.

- Extract the URLs somehow and replace them. But how to cover all the cases?

**Comment by KermanX** [comment]
I forgot that we can use [the `public` directory](https://sli.dev/custom/directory-structure#public) here.

Because it is hard to resolve assets inside Mermaid graph, close this for now.
