### ISSUE TITLE
Crash: The requested module lz-string does not provide an export named 'decompressFromBase64'

### ISSUE THREAD

**Issue by iStefo** [slidevjs/slidev#1341]
**Describe the bug**
When initialising a new project using pnpm create, the public URL stays blank and Chrome logs the error 
```
Uncaught SyntaxError: The requested module '/node_modules/.pnpm/lz-string@1.5.0/node_modules/lz-string/libs/lz-string.js?v=6bd9ceb9' does not provide an export named 'decompressFromBase64' (at ShikiMagicMove.vue:5:10)
```

This is probably related to https://github.com/slidevjs/slidev/commit/e199010f0eba9d0fb7f177d2ebaf2d3537b3592b

**To Reproduce**
1. Create new project using `pnpm create <name>`
2. Open dev server on `/`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Slidev version: v0.48.0-beta.16

**Comment by iStefo** [comment]
One more comment: maybe the install guides should point to a stable version, as this was not a very good first user experience with the software :)

**Comment by antfu** [comment]
v0.48.0-beta.18 should fix it with https://github.com/slidevjs/slidev/commit/76ae95dabc6c062a4f55ed4c4b586eb0a8bc46e4

Thanks for reporting. 

Having the beta version as the latest tag on npm is our intentional strategy to encourage trying and providing feedback. The beta status doesn't necessarily imply it's unstable, but more like a state we are not ready for everything (#1335) and that's why feedbacks are important to us. For the case of this issue, it's an unintentional regression that was introduced back in a few "stable" versions back but only surfaced in the recent change - anyway, thanks for reporting and the suggestions.
