### ISSUE TITLE
Feature request: Camera view shape options

### ISSUE THREAD

**Issue by mika76** [slidevjs/slidev#139]
It would nice to be able to use shapes other than a circle for the camera view? I'm not sure if possible, but a mask or svg shape or something configurable would be amazing!

**Comment by antfu** [comment]
Honestly, we probably won't consider this as a built-in feature. As it's way more tricky to make it work and configurable in an easy way, and I don't feel it's a commonly used features either. Since you can already record them separately, you can actually do much more complex masking or even animations with post-processing. Closing now, thanks for bringing this up.
