### ISSUE TITLE
`magic-move` Scrolling of code not possible when box small

### ISSUE THREAD

**Issue by jolo-dev** [slidevjs/slidev#1531]
**Is your feature request related to a problem? Please describe.**
I use `magic-move` in the `two-cols` layout but the line of code is bigger than the view box. Therefore, I cannot scroll.

Demo: https://stackblitz.com/edit/github-ljrrqh?file=slides.md

**Describe the solution you'd like**
I would like to scroll inside the box.
It basically should work like the way code without `magic-move`.

**Comment by KermanX** [comment]
The problem is because of https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue. If we set `overflow-x` to `auto`, then `overflow-y` can't be `visible`. And for common cases, the code won't get overflowed (also overflowing is not quite pretty), so we may not going to fix this. A workaround could be:

`````md
````md magic-move {class:'!children:overflow-x-auto !children:overflow-y-hidden'}
...
````
`````

**Comment by jolo-dev** [comment]
@KermanX this works and is totally fine :)
