### ISSUE TITLE
Add a quizz components

### ISSUE THREAD

**Issue by yodatak** [slidevjs/slidev#1591]
**Is your feature request related to a problem? Please describe.**
I want to make a course and then do some quizz to make it easy to remind

**Describe the solution you'd like**
A quizz or an addon quizz for slidev

**Describe alternatives you've considered**
Develop some custom vue component but i'm not developer

**Comment by KermanX** [comment]
Closing this issue because not planning to implement this feature in Slidev itself.

FYI, there is a Quiz component for Vue: https://github.com/FriendlyUser/vue-quiz-comp. You can copy [this file](https://github.com/FriendlyUser/vue-quiz-comp/blob/master/src/components/Quiz.vue) to your slides project's `components` folder and use it in you slides.
