### ISSUE TITLE
file open in vscodes on wsl support

### ISSUE THREAD

**Issue by veritem** [slidevjs/slidev#160]
**Describe the bug**
opening the file in the editor using vscode it doesn't work

**To Reproduce**
1. Click on open in the editor arrow, accept opening in  vscode
4. Error message pops in that the file doesn't exist on the disk

![image](https://user-images.githubusercontent.com/53856673/119237554-b5a7bc00-bb3d-11eb-98a3-61702fc8c310.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro wsl ubuntu 20.04
 - Browser: Chrome
 - Slidev version:  0.13.4

**Comment by genzyy** [comment]
@veritem Hey!,  I wasn't able to reproduce this issue.

One thing that I might have done different is that I set up my default code editor in wsl shell to be vscode and then clicking on the editor button opens vscode without any issue.

If your issue still exists, then can you elaborate more please so that I can work on it?
