### ISSUE TITLE
monaco-diff with editorOptions was broken

### ISSUE THREAD

**Issue by lfire** [slidevjs/slidev#1650]
**Describe the bug**
when slidev version on 0.48.2，the monaco-diff is OK
![image](https://github.com/slidevjs/slidev/assets/2528719/b2d24e5d-501c-4b60-8366-b5f2d447456e)

but when update slidev version to 0.49.9, the diff was broken
![image](https://github.com/slidevjs/slidev/assets/2528719/fd3bd686-a0bd-49aa-b493-0866ffaaebea)

eg: https://lfire.github.io/slidev-share/slides/#/19

**To Reproduce**

1. update slidev version to 0.49.9
2. add code block:
```
```ts {monaco-diff} { editorOptions: { lineNumbers: 'on', renderSideBySide: true, useInlineViewWhenSpaceIsLimited: false, readOnly: true } }
export const qsConfig: qs.IParseOptions = {
  allowDots: true,
  depth: 5,
  parameterLimit: 1000,
  arrayLimit: 1000,
  parseArrays: true,
  plainObjects: true,
  strictNullHandling: true,
  ignoreQueryPrefix: true,
};
~~~
export const qsConfig: qs.IParseOptions = {
  parameterLimit: 1000,
  arrayLimit: 1000,
  allowDots: true,
  parseArrays: true,
  depth: 5,
  plainObjects: true,
  strictNullHandling: true
};
```

```
4. run dev script


**Desktop (please complete the following information):**

- OS: MAC
- Browser: chrome
- Slidev version: 0.49.9

**Comment by KermanX** [comment]
I think this issue is caused by https://github.com/slidevjs/slidev/commit/00241ac328add597d9729246d8c88d1f608e4063#diff-d95c3197ddc9f1470185c96336a7842b2ae0b244d4296f197eacddbfe2d62dd8L14-R14

```diff
-  /^```(\w+?)\s*{monaco-diff}\s*?({.*?})?\s*?\n([\s\S]+?)^~~~\s*?\n([\s\S]+?)^```/mg
+  /^```(\w+) *\{monaco-diff\} *(?:(\{[^\n}]*\}) *)?\n([\s\S]+?)^~~~ *\n([\s\S]+?)^```/gm
````
