### ISSUE TITLE
Cannot access remotely with ip address

### ISSUE THREAD

**Issue by Chaotic-chaos** [slidevjs/slidev#175]
Hi, there. Sorry to interrupt. I really enjoy this beautiful project! But there's a problem.

When I run `npm run dev`, then I can access the slides with `localhost:3030` or `127.0.0.1:3030`. But when I use my pc's ip address with the same port `3030`, the browser shows the message that the server refuse this request.

What should I do....

Thx again!

**Comment by dizys** [comment]
I believe this is intentional and an industrial norm. Not exposing dev mode server to the world wide web is the least safety measures you could do.

That being said, relying on Vite, Slidev gives you the option to configure dev host yourself. Refer to [Slidev Docs](https://sli.dev/custom/config-vite.html) and [Vite Docs](https://vitejs.dev/config/#server-host) for this.

But still, don't do it unless you really mean it.

**Comment by Chaotic-chaos** [comment]
All right, I see.

Thx so much! And have a good day~

**Comment by dizys** [comment]
> I believe this is intentional and an industrial norm. Not exposing dev mode server to the world wide web is the least safety measures you could do.
> 
> That being said, slidev has an option under CLI `remote`.
> 
> You should be able to do this to set the dev host to `0.0.0.0`
> 
> ```shell
> $ yarn dev --remote
> ```
> 
> But still, don't do it unless you really mean it.

Please checkout my updated answer. Vite config seems not to work for setting dev server host and port.
