### ISSUE TITLE
Using Line HiLighting in the code block on the last slide page does not work.

### ISSUE THREAD

**Issue by takafumikobayashi** [slidevjs/slidev#179]
**Describe the bug**
Using Line HiLighting in the code block on the last slide page does not work.

<img src="https://user-images.githubusercontent.com/41223057/119505753-3d90fe80-bda8-11eb-9305-0f025ac5eade.png" width=50%>

**To Reproduce**
1. open `slides.md`.
2. move the default sample `Code` page to the last page. 
3. Run `npx slidev` to launch the slide.
4. when you go to the last page, you cannot go to the next slide (the page specified by highlighting) from the bottom left navigation.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3
 - Browser: Google Chrome 90.0.4430.212
 - Slidev version: v0.13.9

**Comment by dizys** [comment]
This is caused due to the fact that the disable states of `<-` and `->` buttons on the toolbar are just simply controlled by the condition: whether there's a page before/after this or not. So code highlighting, `v-click` and any other in-page states that would require clicking to change just all fail to make toolbar navigation buttons aware of them. So basically, this is not only happening to the last page, it also happens to the first page, to both procedural code highlighting and `v-click` controls. I see no quick fix for this. However, a temporary workaround is to use <kbd>←</kbd> and <kbd>→</kbd> buttons on your keyboard to navigate.

**Comment by dizys** [comment]
Working on a fix.

**Comment by takafumikobayashi** [comment]
OK.
I would like to wait for a fix.
Thank you very much.

**Comment by jahirfiquitiva** [comment]
This also happened to me. Adding another slide at the end fixed it.
I'm using v `0.22.7`
