### ISSUE TITLE
Slide attribute "frontmatter" is always "[object Object]"

### ISSUE THREAD

**Issue by benweidig** [slidevjs/slidev#1794]
**Describe the bug**

Each `div.slidev-layout` has an attribute `frontmatter` that's always `[object Object]`

**Minimal reproduction**

1. `npm init slidev@latest`
2. Fill out the necessary things to create and start the project
2. Check HTML

**Environment**

- Slidev version: 0.49.23
- Browser: any
- OS: Debian 12

![Selection_018](https://github.com/user-attachments/assets/1093dc77-fb22-4509-a2df-b985a51e03df)

**Comment by KermanX** [comment]
Thank you for mentioning this. This is because currently, we can't find a way to detect whether the layout component receives a frontmatter property. As a workaround, all frontmatters excluding the known ones and `frontmatter` for the frontmatter object are passed to props. If the layout component doesn't have the corresponding props, these "extra" props will become DOM attributes.

**Comment by antfu** [comment]
That's how Vue works - do you have any runtime problems because of that? Otherwise I'd say just ignore it, it doesn't matter after all

**Comment by benweidig** [comment]
It doesn't cause me any runtime problems.
So far, it's smooth sailing and the best and easiest-to-use slide tool for my purposes!

Just noticed the `[object Object]`, and without any Vue knowledge, it looked like an oversight/possible issue.
However, I somehow missed the referenced issue/PR, even though I searched before creating this one...

Thank you for explaining it to me, as I didn't get far looking at `constants.ts` and `InjectionKey` myself.
