### ISSUE TITLE
<v-click> and markdown headings

### ISSUE THREAD

**Issue by faroit** [slidevjs/slidev#255]
**Describe the bug**
using v-click on markdown headings doesn't work as expected

**To Reproduce**
```html
<v-click>

# Hello World

</v-click>

<v-click>

# Hello World

</v-click>
```
The two headlines are rendered both at the same time instead of rendered after the click

 - Slidev version: v0.20.4

**Comment by Ecotiny** [comment]
If you need a workaround, you can do:
```
<h1 v-click>Hello World</h1>
<h1 v-click>Hello World</h1>
```

**Comment by faroit** [comment]
@Ecotiny but if I can't use markdown, I can't render Math, right?

**Comment by Ecotiny** [comment]
You can in `<span>`. It gets pretty messy if you try to replicate an `<h1>` element with `<span>`, though.
I ended up with:
```html
<span style='font-size: 2rem; line-height:2.25rem; color: var(--slidev-theme-primary);' v-click>$\sqrt{21}$<\span>
```
And this has to be done _before_ a `<h1>` element because slidev has an `opacity: 0.5` style applied to `<p>` tags after `<h1>` tags, and the `<span>` gets put inside a `<p>` tag.
Positioning isn't going to be perfect, there are plenty of other classes that slidev applies that you have to work against, so I wouldn't really recommend it.

**Comment by faroit** [comment]
@Ecotiny okay this is indeed not feasible. Can this be considered a bug then and could be addressed within the scope of this package?

**Comment by antfu** [comment]
https://user-images.githubusercontent.com/11247099/122004852-81938400-cde7-11eb-8991-5f134300ae76.mov

Can not reproduce
