### ISSUE TITLE
Unable to annotate on image

### ISSUE THREAD

**Issue by lyqht** [slidevjs/slidev#394]
**Describe the bug**
I am unable to annotate on an image. A GIF is provided below where I can annotate other parts of the slide but not on top of the image.

**To Reproduce**
![slidev-unable-to-annotate-on-images](https://user-images.githubusercontent.com/35736525/140755422-f4bc64dc-4eff-4757-9c36-99856bb97716.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome

```
  "dependencies": {
    "@slidev/cli": "^0.27.10",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*",
    "slidev-theme-penguin": "^1.1.2",
    "vite-svg-loader": "^3.0.0"
  },
```

**Comment by antfu** [comment]
Probably a z-index issue? (I guess it could be related to your theme) If you find a way to fix it, PR is welcome.

**Comment by isaaccaa** [comment]
As I have met this bug on my theme, the cause of the problem is z-index. `penguin` set the z-index of default contents as **10**, which maybe higher than the ink layer. You may also noticed that the ink can be obscured by the text.

```vue
# default.vue
<div class="my-auto z-10">
      <slot />
</div>
```

It can be solved by set the layer below 0, like `-z-10`. And I recommend setting the z-index of the ink layers to a very large value by default
![ink under the text](https://user-images.githubusercontent.com/59925794/156768689-81e004d4-e2a4-4e85-a96d-d5768a67ae7f.gif)
.

**Comment by tonai** [comment]
This should now be fixed.
Can you confirm ?
