### ISSUE TITLE
how to forbid others presenter mode?

### ISSUE THREAD

**Issue by yuyuexi** [slidevjs/slidev#422]
Hi, there. Thanks for this great work and I really enjoy this project!

I am not sure if this is a feature or I can find someway to fix it: I want to share my slides to other audiences, but it is annoying that everyone accessible to this slides can use the presenter mode. Is there any method I can forbid this and only use the presenter mode by myself?

**Comment by antfu** [comment]
I guess we could have something like http://localhost:3000/1?view that hides the UI so you can share the URL to others? If so, I am open for PR :)

**Comment by yuyuexi** [comment]
> I guess we could have something like http://localhost:3000/1?view that hides the UI so you can share the URL to others? If so, I am open for PR :)

Thanks for your timely reply!

I tried [](http://localhost:3000/1?view), however I can also enter presenter mode from it. I do not know if I understand your suggestion correctly?

**Comment by antfu** [comment]
Yes, it's not there for now - I was proposing a feature. If it looks good to you, maybe you can try to implement it and send a PR.

**Comment by tonai** [comment]
I think this is an interesting issue when you want to give access to your presentation to others, but don't want them to go to presenter view and start messing the main presentation you are doing.
I don't think having a parameter in the URL is enough, because someone can still change it and go to the presenter view.

Maybe we can have a workflow like this one:
* add a frontmatter option in the slides like `privacy: 'private'` (will be `'public'` by default)
* if privacy is `'private'` then:
  * hide the presenter button in the control bar
  * generate a token and display it when launching the dev server: `presenter mode  > http://localhost:3030/presenter?token=abc`
  * only allow access to `/presenter` to people who have the right token in the URL (only if you are on dev mode)

What do you think ?
