### ISSUE TITLE
Drawing on Surface with Surface Pen but get little dash

### ISSUE THREAD

**Issue by isaaccaa** [slidevjs/slidev#504]
**Drawing & Annotations on Surface with Surface Pen**
Everything was fine when I used the iPad to draw on the slider. But when I use the Edge browser on Surface Pro with a Surface Pen, I can only get a lot of little dash. 

![Draw on Surface](https://user-images.githubusercontent.com/59925794/156776248-bc4c16eb-18b9-49fc-9c25-5d2f5e9cb20b.jpg)

When I draw a short line and continue to drag, Edge treats the input from the Surface Pen as a forward/backward gesture.However, drauu's [live demo](https://drauu.netlify.app/) works very well on my Surface.

What should I do to make it correctly to draw on Surface, or is it some settings missed on slidev?
**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Slidev version: v0.28.2

**Comment by antfu** [comment]
Since I don't have a Surface to test out, I guess you might need to try to debug and figure out yourself 😅

**Comment by twitwi** [comment]
I randomly tried it on an android phone (that uses firefox mobile) and I see the same kind of behavior.

**Comment by barais** [comment]
Hello, thanks for the great framework. 
I got the same behavior with chrome, Kiwi on Pixel or Android tablet. Site is deployed on github page

**Comment by Celeborn2BeAlive** [comment]
Hi, same issue, on pen tablet and android phone (brave browser), you can check that here: https://slidev-template.vercel.app/1

https://drauu.netlify.app/ is working perfectly fine on both devices, so I guess it's a configuration issue, or components messing up each others, on the slidev side.

I hope it's easy to fix because IMO drawing on slides is a killer feature, that's the only thing that makes me use powerpoint, and I really want to fully transition to slidev :)

**Comment by twitwi** [comment]
@tonai can this one be closed?

**Comment by tonai** [comment]
Yes this has been fixed and released in version 0.31.3
