### ISSUE TITLE
KaTeX rendering error

### ISSUE THREAD

**Issue by ChiMaoShuPhy** [slidevjs/slidev#663]
The katex inline math and display math failed to rendering expressions like `${{C}_0}$`, `${{C}^0}$`.
It is the curly braces around C causing this problem, although in the example the curly braces can be dropped but not in the actual slide code. A work around is to insert space such as `${{ C }_0}$`.

**To Reproduce**
1. `slidev` to initialize a slide 
2. put `${{C}_0}$` in the md file
3. See the error in attached picture
![2022-07-27_00-56](https://user-images.githubusercontent.com/16471347/181065891-2d478d6e-58ac-45fd-a51d-0f4c2d1cee2e.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu-22.04 LTS
 - Browser: Firefox, Chromium
 - Slidev version: v0.34.3

**Comment by twitwi** [comment]
The issue comes from the fact that katex generates code that (also) contains the raw typed expression, so it contains `{{` that is used for vue expressions.

To be sure, can you confirm that what works around the problem is to add a space between the two `{` (I still get an error with the workaround mentioned in the issue description).
