### ISSUE TITLE
Vite transformIndexHtml hook does not run

### ISSUE THREAD

**Issue by Tahul** [slidevjs/slidev#808]
**Describe the bug**

Using a custom `vite.config.ts` works fine, but if I add a plugin that has `transformIndexHtml` hook, then it does not run that hook.

**To Reproduce**

https://stackblitz.com/edit/slidev-jcu8rm?file=vite.config.ts

Just run this reproduction ; you'll see in the vite.config that `transform` hook from the plugin runs, not `transformIndexHtml`.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chromium
 - Slidev version: 0.38.2

**Comment by Tahul** [comment]
Hey @tonai :)

Thanks for answering.

I am trying to add a Vite plugin to the stack that depends on running that hook.

For now, I worked around it, but I still think it's worth knowing why this hook does not run in that context.

**Comment by tonai** [comment]
I Just tried the following:
* I commented the `configureServer` hook here https://github.com/slidevjs/slidev/blob/main/packages/slidev/node/plugins/extendConfig.ts#L93
* I created a `index.html` file in the root of the `demo/starter` repository
* I added a plugin with the `transformIndexHtml` hook and it gets called in that case when I run the dev server of the starter demo

So the `transformIndexHtml` hook is not triggered because slidev use that `configureServer` hook.
It uses this to send a custom html content and allow to initialize a slidev project without any `index.html` file inside it.

So maybe it is a vite bug, because the `transformIndexHtml` should maybe have been triggered even if we use the `configureServer` hook.
Or maybe you can also use the `configureServer` hook to change the `index.html` content.

**Comment by Tahul** [comment]
@tonai Thank you so much for such clear explanations.

I'll take your insights to work around my issue.
