### ISSUE TITLE
代码块有花括号时无法展示

### ISSUE THREAD

**Issue by ltaoo** [slidevjs/slidev#95]
代码块生成 `html` 后还会保留 `{{}}`，此时将 `html` 插入 `<template>` 作为内容，`{{}}` 就作为语法被处理所以不展示了。

示例
https://codesandbox.io/s/fancy-dawn-j344h?file=/src/README.md

![image](https://user-images.githubusercontent.com/15319872/118091409-60f99800-b3fd-11eb-944d-60e7db3e2282.png)

**Comment by Ahacad** [comment]
括号里面加东西也会导致报错，应该是和 Vue 语法冲突了？

**Comment by Ahacad** [comment]
这个问题直接使用 vite 和 [vite-plugin-md](https://github.com/antfu/vite-plugin-md) 也会出现，应该是依赖的 `vite-plugin-md` 的锅

**Comment by Ahacad** [comment]
This actually cannot be easily fixed by `\{`, the backslash will be displayed, see the picture below, I wrote the lines in markdown.

```
function updateUser(id: number, update: Partial<User>) {
  const user = getUser(id)
  const newUser = {...user, ...update}  
  saveUser(id, newUser)
}
{{}}
```

![20210513-19:48:06](https://user-images.githubusercontent.com/51874356/118121746-7f26be80-b424-11eb-89e5-0fd04824d745.png)



https://github.com/slidevjs/slidev/blob/103da55c4e7382d76a72b5d2a368525e9538f0ab/packages/slidev/node/plugins/markdown.ts#L143

Seems that character references are still needed.
