### ISSUE TITLE
mermaid diagram scaling not working

### ISSUE THREAD

**Issue by temco** [slidevjs/slidev#952]
when I define a mermaid diagram with the markdown syntax like ```mermaid {scale: 0.5} xxxx..xxxx ```, the diagram won't be scaled as my setting, while plantuml does it well. Even the official demo `slides.md` keeps this performance, in the page 9.

**To Reproduce**
1. Go to page 9 of the demo slides
2. Edit the code by modifying ` ```mermaid {scale: 0.5}`, ` ```mermaid {theme: 'neutral', scale: 0.8}`, and ` ```plantuml {scale: 0.7}`
3. the two mermaid diagram don't change the scaling, but the plantuml one changes

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.3
 - Browser: Chrome 111.0.5563.146
 - Slidev version: 0.4.10 (when I used the 0.4.3 version, it keeped working well, however I cannot install that version by `npm init slidev@0.40.3`, which will install 0.40.10 instead)

**Comment by Goregius** [comment]
I've had this issue as well, plantuml works fine but mermaid doesn't. Also The scaling in `0.40.3` works for me except for when exporting to PDF.

**Comment by Goregius** [comment]
I can see that in the new version width is set to "100%" but before it was correctly set without a width and a specific height.

Looking at the code could it be due to this change: https://github.com/slidevjs/slidev/commit/1bd089f275003d82dca8fb4882d37c5697d9783e#diff-022b37b95f2f88a54fec1b515d099850ab31d902bbe07b4844a83c7ab5b85e5b. 

I'm not too familiar with Vue 3 but could it be overriding the `watchEffect` calls below it specifically the bottom one which sets the height/width based on the scale?

**Comment by erlebach** [comment]
Nobody has the answer to this questions? Might as well remove Mermaid from the slide stack.

**Comment by erlebach** [comment]
Hi @temco, 
Thanks for the response. I tried the following and it worked!!
```
\`\`\`mermaid {}
<Transform :scale=2>
pie showData
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
</Transform>
\`\`\`
```

**Comment by tkgregory** [comment]
Thanks @erlebach. Your example worked, with one adjustment:

````
<Transform :scale=2>
```mermaid {}
pie showData
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
```
</Transform>
````
