### ISSUE TITLE
Customize presenter mode

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#996]
Allow us to create a vue template under `layouts/_presenter.vue` by default that has 3 `<slots>` for the current, next and notes panels so we can lay them out in any way. And let us provide `<style>` in that vue template where we can write css to style the generated html only in the notes panel. This will make any customization possible for presenter mode.

**Comment by willklein** [comment]
I really like this proposal. I just recorded a conference talk and I needed my speaker notes moved for better access. I found myself going into the DOM, deleting elements, and changing classes to get the speaker notes right up at the top and center, below my camera. I didn't need the preview for the next slide or even the current slide at all, but I can also see personalizing their placement. Ideally I'd be able to reposition and resize elements from the presenter view rather than using CSS or editing a template, but that would have been fine too.

**Comment by KermanX** [comment]
For people who find this issue, here is a solution: https://github.com/slidevjs/slidev/issues/1095#issuecomment-2061108714
